# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_sps_dec_usd_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from f_rutas import *

class Ui_converter_window(object):
    
    def setupUi(self, converter_window):
        
        # Se guarda la ruta absoluta a la imagen para usar como icono.
        ruta_icono=resource_path('spl-logo.png')

        # Se guardan las rutas absolutas a las imágenes del DEC y SPS.
        ruta_imagen_dec=resource_path('dec-logo.png')
        ruta_imagen_sps=resource_path('sps-logo.png')

        converter_window.setObjectName("converter_window")
        converter_window.resize(409, 204)
        icon = QtGui.QIcon()

        # Ruta absoluta.
        icon.addPixmap(QtGui.QPixmap(ruta_icono), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        converter_window.setWindowIcon(icon)
        self.lbl_dec = QtWidgets.QLabel(converter_window)
        self.lbl_dec.setGeometry(QtCore.QRect(40, 70, 21, 21))
        self.lbl_dec.setText("")

        # Ruta absoluta.
        self.lbl_dec.setPixmap(QtGui.QPixmap(ruta_imagen_dec))
        self.lbl_dec.setScaledContents(True)
        self.lbl_dec.setObjectName("lbl_dec")
        self.lbl_sps = QtWidgets.QLabel(converter_window)
        self.lbl_sps.setGeometry(QtCore.QRect(40, 111, 21, 20))
        self.lbl_sps.setText("")

        # Ruta absoluta.
        self.lbl_sps.setPixmap(QtGui.QPixmap(ruta_imagen_sps))
        self.lbl_sps.setScaledContents(True)
        self.lbl_sps.setObjectName("lbl_sps")
        self.lbl_title = QtWidgets.QLabel(converter_window)
        self.lbl_title.setGeometry(QtCore.QRect(70, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.layoutWidget = QtWidgets.QWidget(converter_window)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 276, 64))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_dec = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_dec.setStyleSheet("    QLineEdit:focus {\n"
"        border: 1px solid purple;\n"
"    }")
        self.lineEdit_dec.setObjectName("lineEdit_dec")
        self.horizontalLayout_4.addWidget(self.lineEdit_dec)
        self.lineEdit_usd_dec = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_usd_dec.setStyleSheet("    QLineEdit:focus {\n"
"        border: 1px solid purple;\n"
"    }")
        self.lineEdit_usd_dec.setObjectName("lineEdit_usd_dec")
        self.horizontalLayout_4.addWidget(self.lineEdit_usd_dec)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_sps = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_sps.setStyleSheet("    QLineEdit:focus {\n"
"        border: 1px solid yellow;\n"
"    }")
        self.lineEdit_sps.setText("")
        self.lineEdit_sps.setObjectName("lineEdit_sps")
        self.horizontalLayout_5.addWidget(self.lineEdit_sps)
        self.lineEdit_usd_sps = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_usd_sps.setStyleSheet("    QLineEdit:focus {\n"
"        border: 1px solid yellow;\n"
"    }")
        self.lineEdit_usd_sps.setObjectName("lineEdit_usd_sps")
        self.horizontalLayout_5.addWidget(self.lineEdit_usd_sps)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.lbl_bottom_icon = QtWidgets.QLabel(converter_window)
        self.lbl_bottom_icon.setGeometry(QtCore.QRect(350, 160, 51, 41))
        self.lbl_bottom_icon.setText("")

        # Se usa ruta absoluta.
        self.lbl_bottom_icon.setPixmap(QtGui.QPixmap(ruta_icono))
        self.lbl_bottom_icon.setScaledContents(True)
        self.lbl_bottom_icon.setObjectName("lbl_bottom_icon")
        self.lbl_author = QtWidgets.QLabel(converter_window)
        self.lbl_author.setGeometry(QtCore.QRect(10, 180, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_author.setFont(font)
        self.lbl_author.setObjectName("lbl_author")
        self.lbl_author_2 = QtWidgets.QLabel(converter_window)
        self.lbl_author_2.setGeometry(QtCore.QRect(140, 180, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_author_2.setFont(font)
        self.lbl_author_2.setObjectName("lbl_author_2")
        self.lbl_author_3 = QtWidgets.QLabel(converter_window)
        self.lbl_author_3.setGeometry(QtCore.QRect(10, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_author_3.setFont(font)
        self.lbl_author_3.setObjectName("lbl_author_3")

        self.retranslateUi(converter_window)
        QtCore.QMetaObject.connectSlotsByName(converter_window)

    def retranslateUi(self, converter_window):
        _translate = QtCore.QCoreApplication.translate
        converter_window.setWindowTitle(_translate("converter_window", "DEC & SPS to USD Converter"))
        self.lbl_title.setText(_translate("converter_window", "DEC & SPS to USD Converter"))
        self.lineEdit_dec.setPlaceholderText(_translate("converter_window", "DEC"))
        self.lineEdit_usd_dec.setPlaceholderText(_translate("converter_window", "USD/DEC"))
        self.lineEdit_sps.setPlaceholderText(_translate("converter_window", "SPS"))
        self.lineEdit_usd_sps.setPlaceholderText(_translate("converter_window", "USD/SPS"))
        self.lbl_author.setText(_translate("converter_window", "GitHub: antoniojg92"))
        self.lbl_author_2.setText(_translate("converter_window", "| Hive: antoniojg"))
        self.lbl_author_3.setText(_translate("converter_window", "Created by:"))
